
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: community_Posts_development

 
test:
  <<: *default
  database: community_Posts_test

production:
  <<: *default
  database: community_Posts_production
  username: community_Posts
  password: <%= ENV['COMMUNITY_POSTS_DATABASE_PASSWORD'] %>
